# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    ports:
      - "5432:5432"
    build: scripts/postgres/
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=postgres
    user: "1000:50"
volumes:
  data:
    driver: local
