CREATE TABLE IF NOT EXISTS DUMMY (
   id        bigserial PRIMARY KEY,
   dummy_1 CHARACTER VARYING (255),
   dummy_2 CHARACTER VARYING (255),
   dummy_3 CHARACTER VARYING (255),
   dummy_4 INTEGER
);